---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/fluxctl version
    register: fluxctl_test_output
  - name: fluxctl version
    debug:
      msg: '{{ fluxctl_test_output.stdout }}'
